(function(){
  var form=$('#form'),save=$('#save'),state=$('#save-state'),publicLink=$('#public_sharing_enabled'),embedding=$('#embedding_enabled'),embeddingRow=$('#embedding-row'),impact=$('#public-impact');
  var original={},publicBoards=0,saving=false,developerOriginal={},developerSaving=false;
  function values(){return {site_name:$('#site_name').value.trim(),timezone:$('#timezone').value,public_scheme:$('#public_scheme').value,custom_domain:$('#custom_domain').value.trim().toLowerCase(),public_port:Number($('#public_port').value)||0,public_sharing_enabled:publicLink.checked,embedding_enabled:embedding.checked};}
  function changed(){var current=values();return Object.keys(current).some(function(key){return current[key]!==original[key];});}
  function syncAccess(){var enabled=publicLink.checked;embedding.disabled=!enabled;embeddingRow.classList.toggle('is-disabled',!enabled);if(!enabled)embedding.checked=false;impact.hidden=enabled||!publicBoards;impact.textContent=publicBoards?'关闭后，'+publicBoards+' 个已发布仪表盘的公开链接将立即不可访问。':'';}
  function syncAddressPreview(){var scheme=$('#public_scheme').value,domain=$('#custom_domain').value.trim().toLowerCase(),port=Number($('#public_port').value)||0,preview=$('#public-address-preview');if(!domain&&scheme==='auto'&&!port){preview.textContent='自动使用当前访问地址';return;}var protocol=scheme==='auto'?(location.protocol==='https:'?'https':'http'):scheme;var host=domain||location.hostname;preview.textContent=protocol+'://'+host+(port?':'+port:'');}
  function syncState(){syncAccess();syncAddressPreview();if(saving)return;state.textContent=changed()?'有未保存的更改':'已同步';state.className='save-state'+(changed()?' dirty':'');}
  function fill(settings){original={site_name:settings.site_name||'Topbase',timezone:settings.timezone||'Asia/Shanghai',public_scheme:settings.public_scheme||'auto',custom_domain:settings.custom_domain||'',public_port:Number(settings.public_port)||0,public_sharing_enabled:!!settings.public_sharing_enabled,embedding_enabled:!!settings.embedding_enabled};$('#site_name').value=original.site_name;$('#timezone').value=original.timezone;$('#public_scheme').value=original.public_scheme;$('#custom_domain').value=original.custom_domain;$('#public_port').value=original.public_port||'';publicLink.checked=original.public_sharing_enabled;embedding.checked=original.embedding_enabled;syncState();}
  function loadAppDatabase(){return api('/api/admin/application-database').then(function(status){var sqlite=status.engine==='sqlite';$('#appdb-engine').textContent=sqlite?'SQLite 本地应用数据库':(status.engine==='mysql'?'MySQL 应用数据库':'PostgreSQL 应用数据库');$('#appdb-description').textContent='Schema 版本 '+status.schema_version+(sqlite?' · 数据保存在当前节点':' · 可用于 RDS 与多节点部署');$('#appdb-mode').textContent=sqlite?'开发体验':'生产正式';$('#appdb-warning').hidden=!sqlite;$('#migrate-appdb').hidden=!status.migration_available;if(status.migration_completed){$('#appdb-result').hidden=false;$('#appdb-result').innerHTML='<strong>数据迁移已完成</strong><p>完成时间：'+esc(status.migration_completed_at)+'。当前进程仍以启动配置为准；请确认生产连接参数已写入环境变量并完成重启。</p>';}}).catch(function(error){toast(error.message);});}
  function load(){return Promise.all([api('/api/admin/settings'),api('/api/dashboards').catch(function(){return []}),loadAppDatabase()]).then(function(result){publicBoards=(result[1]||[]).filter(function(board){return board.public_uuid;}).length;fill(result[0]);}).catch(function(error){toast(error.message);});}
  form.addEventListener('input',syncState);form.addEventListener('change',syncState);
  form.addEventListener('submit',function(event){event.preventDefault();if(saving||!form.reportValidity())return;saving=true;save.disabled=true;state.textContent='正在保存…';state.className='save-state saving';api('/api/admin/settings','PUT',values()).then(function(settings){fill(settings);toast('工作区设置已保存');}).catch(function(error){toast(error.message);}).finally(function(){saving=false;save.disabled=false;syncState();});});
  $('#migrate-appdb').addEventListener('click',async function(){var values=await formDialog({kicker:'生产正式环境',title:'迁移应用数据库',description:'目标必须是专用于 Topbase 的空数据库。系统先初始化结构，再在一个事务内复制并校验数据；当前 SQLite 不会被删除。',size:'wide',confirmText:'检查并继续',fields:[{name:'engine',label:'数据库类型',type:'select',value:'postgres',options:[{value:'postgres',label:'PostgreSQL / RDS PostgreSQL'},{value:'mysql',label:'MySQL / RDS MySQL'}],required:true},{name:'host',label:'主机地址',placeholder:'内网或 RDS 地址',required:true},{name:'port',label:'端口',type:'number',placeholder:'PostgreSQL 5432 / MySQL 3306'},{name:'database',label:'数据库名称',required:true},{name:'schema',label:'PostgreSQL Schema',value:'public',help:'MySQL 会忽略此项。'},{name:'username',label:'用户名',required:true},{name:'password',label:'密码',type:'password'},{name:'tls_mode',label:'TLS 模式',type:'select',value:'prefer',options:[{value:'prefer',label:'优先加密（开发/内网）'},{value:'require',label:'必须加密'},{value:'verify-full',label:'校验证书与主机名'},{value:'disable',label:'不使用 TLS'}]}]});if(!values)return;var approved=await confirmDialog({kicker:'一次性迁移',title:'已备份并确认目标为空库？',description:'开始后会在目标数据库创建 Topbase 表并复制全部项目数据。成功后此实例不能再次执行生产迁移；你仍需修改部署环境变量并重启。',confirmText:'开始迁移'});if(!approved)return;var button=$('#migrate-appdb');button.disabled=true;button.textContent='正在迁移…';try{var result=await api('/api/admin/application-database/migrate','POST',{engine:values.engine,host:values.host,port:Number(values.port)||0,database:values.database,schema:values.schema,username:values.username,password:values.password,tls_mode:values.tls_mode,confirmed:true});var report=result.report||{};$('#appdb-result').hidden=false;$('#appdb-result').innerHTML='<strong>已复制 '+Number(report.rows||0)+' 行、'+Number(report.tables||0)+' 张表</strong><p>'+esc(result.next_step||'请修改部署配置并重启 Topbase。')+'</p>';toast('生产数据库迁移完成');await loadAppDatabase();}catch(error){toast(error.message);}finally{button.disabled=false;button.textContent='迁移到生产环境';}});
  function developerValues(){return {enabled:$('#developer-enabled').checked,allow_personal_keys:$('#developer-personal-keys').checked,allow_analysis_write:$('#developer-analysis-write').checked,default_key_ttl_days:Number($('#developer-key-ttl').value),max_query_rows:Number($('#developer-max-rows').value),public_base_url:$('#developer-public-url').value.trim()};}
  function developerChanged(){var current=developerValues();return Object.keys(current).some(function(key){return current[key]!==developerOriginal[key];});}
  function syncDeveloperState(){var enabled=$('#developer-enabled').checked;$('.developer-card').classList.toggle('is-disabled',!enabled);$('#developer-state').textContent=enabled?'已启用':'未启用';$('#developer-state').className='account-state'+(enabled?' active':'');if(developerSaving)return;$('#developer-save-state').textContent=developerChanged()?'有未保存的更改':'已同步';}
  function fillDeveloper(settings){developerOriginal={enabled:!!settings.enabled,allow_personal_keys:!!settings.allow_personal_keys,allow_analysis_write:!!settings.allow_analysis_write,default_key_ttl_days:Number(settings.default_key_ttl_days||0),max_query_rows:Number(settings.max_query_rows||200),public_base_url:settings.public_base_url||''};$('#developer-enabled').checked=developerOriginal.enabled;$('#developer-personal-keys').checked=developerOriginal.allow_personal_keys;$('#developer-analysis-write').checked=developerOriginal.allow_analysis_write;$('#developer-key-ttl').value=String(developerOriginal.default_key_ttl_days);if(!$('#developer-key-ttl').value){var option=document.createElement('option');option.value=String(developerOriginal.default_key_ttl_days);option.textContent=developerOriginal.default_key_ttl_days+' 天';$('#developer-key-ttl').appendChild(option);$('#developer-key-ttl').value=option.value;}$('#developer-max-rows').value=developerOriginal.max_query_rows;$('#developer-public-url').value=developerOriginal.public_base_url;syncDeveloperState();}
  function renderDeveloperKeys(keys){$('#developer-key-count').textContent=keys.length+' 个';if(!keys.length){$('#developer-key-list').innerHTML='<div class="developer-empty">尚未签发 API Key。启用开发者模式后，用户可在个人中心创建。</div>';return;}$('#developer-key-list').innerHTML=keys.map(function(key){var expiry=key.expires_at?(key.expired?'已于 ':'有效至 ')+new Date(key.expires_at).toLocaleDateString('zh-CN'):'永久有效';return '<article class="developer-key-row"><div><b>'+esc(key.name)+'</b><small>'+esc(key.prefix)+'••••</small></div><div><b>'+esc(key.owner_name||'未知成员')+'</b><small>'+esc(key.owner_email||key.user_id||'—')+'</small></div><div><b class="'+(key.expired?'key-expired':'')+'">'+esc(expiry)+'</b><small>创建于 '+esc(new Date(key.created_at).toLocaleDateString('zh-CN'))+'</small></div><button class="secondary danger-subtle" type="button" data-admin-revoke-key="'+esc(key.id)+'">撤销</button></article>';}).join('');$$('[data-admin-revoke-key]',$('#developer-key-list')).forEach(function(button){button.onclick=async function(){var approved=await confirmDialog({kicker:'开发者模式',title:'撤销这个 API Key？',description:'使用它的 MCP、CLI 和自动化程序会立即停止工作，已创建的分析不会被删除。',confirmText:'撤销密钥',tone:'danger'});if(!approved)return;button.disabled=true;try{await api('/api/admin/api-keys/'+encodeURIComponent(button.dataset.adminRevokeKey),'DELETE');toast('API Key 已撤销');await loadDeveloper();}catch(error){toast(error.message);button.disabled=false;}};});}
  function loadDeveloper(){return Promise.all([api('/api/admin/developer-settings'),api('/api/admin/api-keys')]).then(function(result){fillDeveloper(result[0]);renderDeveloperKeys(result[1]);}).catch(function(error){toast(error.message);});}
  $$('.developer-card input,.developer-card select').forEach(function(control){control.addEventListener('input',syncDeveloperState);control.addEventListener('change',syncDeveloperState);});
  $('#save-developer').addEventListener('click',async function(){if(developerSaving)return;var maxRows=$('#developer-max-rows');if(!maxRows.reportValidity())return;developerSaving=true;this.disabled=true;$('#developer-save-state').textContent='正在保存…';try{var saved=await api('/api/admin/developer-settings','PUT',developerValues());fillDeveloper(saved);toast(saved.enabled?'开发者模式设置已生效':'开发者模式已关闭，所有 API Key 已停止访问');}catch(error){toast(error.message);}finally{developerSaving=false;this.disabled=false;syncDeveloperState();}});
  load();loadDeveloper();
}());
