(function(){
  var hooks=[],subs=[];var e=function(v){return esc(v||'')};var date=function(v){return v?new Date(v).toLocaleString('zh-CN'):'未发送'};var presets={text:function(title,body){return JSON.stringify({msg_type:'text',content:{text:title+'\n'+body}})},post:function(title,body){return JSON.stringify({msg_type:'post',content:{post:{'zh-CN':{title:title,content:[[{tag:'text',text:body}]]}}}})},card:function(title,body){return JSON.stringify({msg_type:'interactive',card:{header:{title:{tag:'plain_text',content:title},template:'blue'},elements:[{tag:'div',text:{tag:'lark_md',content:body}}]}})}};
  function q(id){return $('#'+id)}
  function draw(){q('hooks').innerHTML=hooks.map(function(h){return '<article class="hook-card"><h3>'+e(h.name)+'</h3><div class="hook-meta"><span>'+e(h.provider)+'</span><span>'+(h.enabled?'启用':'已暂停')+'</span><span>'+e(h.template_type||'text')+'</span></div><p>'+e(h.url)+'</p><div class="hook-actions"><button class="secondary" data-edit="'+e(h.id)+'">编辑</button><button class="ghost" data-toggle="'+e(h.id)+'">'+(h.enabled?'暂停':'启用')+'</button><button class="danger" data-remove="'+e(h.id)+'">删除</button></div></article>'}).join('')||'<p class="panel-help">尚未创建 Webhook 通道。</p>';
    var mode=q('sub-filter').value,word=q('sub-search').value.toLowerCase(),rows=subs.filter(function(s){return(mode==='all'||(mode==='enabled')===!!s.enabled)&&(!word||(s.dashboard_id+' '+s.channel).toLowerCase().includes(word))});q('subscriptions').innerHTML=rows.map(function(s){return '<tr><td><b>'+e(s.dashboard_id)+'</b><small>'+e(s.id)+'</small></td><td>'+e(s.channel)+'</td><td>'+e(s.cron)+'<small>'+e(s.timezone)+'</small></td><td>'+date(s.last_run_at)+'</td><td><span class="status '+(s.enabled?'on':'off')+'">'+(s.enabled?'启用':'已暂停')+'</span></td><td class="actions"><button class="secondary" data-run="'+e(s.id)+'">验证</button><button class="ghost" data-sub="'+e(s.id)+'" data-enabled="'+s.enabled+'">'+(s.enabled?'暂停':'启用')+'</button><button class="danger" data-del="'+e(s.id)+'">删除</button></td></tr>'}).join('')||'<tr><td colspan="6">暂无订阅</td></tr>';bind()}
  async function edit(id){var h=hooks.find(function(x){return x.id===id})||{id:'hook_'+Date.now(),name:'新群通知',provider:'feishu',enabled:true,template_type:'text'};var base=await formDialog({title:id==='new'?'创建 Webhook':'编辑 Webhook',description:'选择预置消息类型后，只需填写业务内容；系统会生成对应平台的消息 JSON。',fields:[{name:'name',label:'通道名称',value:h.name,required:true},{name:'provider',label:'平台',type:'select',value:h.provider,options:['feishu','dingtalk','wecom','generic'].map(function(x){return{value:x,label:x}})},{name:'url',label:'Webhook URL',value:h.url,required:true},{name:'secret',label:'签名密钥',type:'password',value:'',help:'留空会保留原密钥。'},{name:'template_type',label:'消息样式',type:'select',value:h.template_type,options:[{value:'text',label:'文本消息（预置）'},{value:'post',label:'富文本（飞书预置）'},{value:'card',label:'消息卡片（飞书预置）'},{value:'custom',label:'自定义 JSON'}]}]});if(!base)return;var content;if(base.template_type==='custom'){content=await formDialog({title:'编辑自定义 JSON',description:'仅自定义 JSON 需要手动编辑。可使用 {{title}} 与 {{body}} 变量。',fields:[{name:'template',label:'模板 JSON',type:'textarea',value:h.template||'{"msg_type":"text","content":{"text":"{{title}}\\n{{body}}"}}',required:true}]});if(!content)return;base.template=content.template}else{content=await formDialog({title:'配置消息内容',description:'这是 '+({text:'文本消息',post:'富文本',card:'消息卡片'}[base.template_type])+' 的预置模板。发送时 {{title}}、{{body}} 将由订阅内容自动替换。',fields:[{name:'title',label:'默认标题',value:h.template_title||'Topbase 通知',required:true},{name:'body',label:'默认正文',type:'textarea',value:h.template_body||'{{body}}',required:true}]});if(!content)return;base.template_title=content.title;base.template_body=content.body;base.template=presets[base.template_type](content.title,content.body)}Object.assign(h,base,{enabled:h.enabled!==false});if(!hooks.some(function(x){return x.id===h.id}))hooks.push(h);save()}
  function save(){api('/api/webhooks','PUT',hooks).then(function(){toast('Webhook 已保存');load()}).catch(function(x){toast(x.message)})}
  function bind(){$$('[data-edit]').forEach(function(b){b.onclick=function(){edit(b.dataset.edit)}});$$('[data-toggle]').forEach(function(b){b.onclick=function(){var h=hooks.find(function(x){return x.id===b.dataset.toggle});h.enabled=!h.enabled;save()}});$$('[data-remove]').forEach(function(b){b.onclick=async function(){if(await confirmDialog({title:'删除 Webhook？',description:'使用该通道的订阅将无法继续投递。',tone:'danger',confirmText:'删除'})){hooks=hooks.filter(function(x){return x.id!==b.dataset.remove});save()}}});$$('[data-run]').forEach(function(b){b.onclick=function(){act('/api/subscriptions/'+b.dataset.run+'/run','POST',{},'已发起验证')}});$$('[data-sub]').forEach(function(b){b.onclick=function(){act('/api/subscriptions/'+b.dataset.sub,'PUT',{enabled:b.dataset.enabled!=='true'},'状态已更新')}});$$('[data-del]').forEach(function(b){b.onclick=async function(){if(await confirmDialog({title:'删除订阅？',tone:'danger',confirmText:'删除'}))act('/api/subscriptions/'+b.dataset.del,'DELETE',null,'订阅已删除')}})}
  function act(u,m,b,t){api(u,m,b).then(function(){toast(t);load()}).catch(function(x){toast(x.message)})}
  function load(){Promise.all([api('/api/webhooks'),api('/api/subscriptions'),api('/api/admin/notifications')]).then(function(r){hooks=r[0];subs=r[1];q('history').innerHTML=r[2].map(function(n){return '<tr><td>'+date(n.created_at)+'</td><td>'+e(n.title)+'</td><td>'+e(n.body)+'</td></tr>'}).join('')||'<tr><td colspan="3">暂无记录</td></tr>';draw()}).catch(function(x){toast(x.message)})}
  q('add-hook').onclick=function(){edit('new')};q('sub-filter').onchange=draw;q('sub-search').oninput=draw;load()
}());
